version: '3'

services:
  application:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      WAIT_HOSTS: db
      APPLICATION_PORT: 3000
    command: ./entrypoint.sh
    depends_on:
      - db
    volumes:
      - ./:/opt/PopcornStore

  db:
    image: mysql:8.0.20
    ports:
      - 3306
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: skydc007+1
