version: '3'

services:
  db:
    image: mysql:8.0.20
    command: [--default-authentication-plugin=mysql_native_password]
    ports:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: skydc007+1
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: skydc007+1

  application:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      APPLICATION_PORT: 3000
      MYSQL_HOST: db
    command: ./entrypoint.sh
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - ./:/opt/PopcornStore